name: PHPUnit Tests

on:
  push:
    branches: [ main, actions/add-workflow ]
  pull_request:
    branches: [ main, actions/add-workflow ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1 # or alternative dependency management
      - name: Luhn
        uses: php-actions/phpunit@v1
        with:
          bootstrap: wp-content/plugins/wc-invoice-payment-gateway/vendor/autoload.php
          configuration: wp-content/plugins/wc-invoice-payment-gateway/tests
