name: PHPUnit Tests

on:
  push:
    branches: [ main, actions/add-workflow ]
  pull_request:
    branches: [ main, actions/add-workflow ]

jobs:
 build-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./wp-content/plugins/wc-invoice-payment-gateway

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: Luhn Tests
        uses: php-actions/phpunit@v1
        with:
          bootstrap: vendor/autoload.php
          command: tests
