name: PHPUnit Tests

on:
  push:
    branches: [ main, actions/add-workflow ]
  pull_request:
    branches: [ main, actions/add-workflow ]

jobs:
 luhn-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wp-content/plugins/wc-invoice-payment-gateway

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: php-actions/phpunit@v1
        with:
          bootstrap: vendor/autoload.php
      - name: Run Luhn Tests
        run: phpunit tests
