name: PHPUnit Tests

on:
  push:
    branches: [ main, actions/add-workflow ]
  pull_request:
    branches: [ main, actions/add-workflow ]

jobs:
 luhn-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        uses: php-actions/composer@v4
        with:
          args: --working-dir wp-content/plugins/wc-invoice-payment-gateway
      - name: Setup PHPUnit
        uses: php-actions/phpunit@v1
        with:
          args: --no-configuration
      - name: Run Luhn Tests
        working-directory: wp-content/plugins/wc-invoice-payment-gateway
        run: phpunit --bootstrap 'wp-content/plugins/wc-invoice-payment-gateway/vendor/autoload.php' tests
