name: PHPUnit Tests

on:
  push:
    branches: [ main, actions/add-workflow ]
  pull_request:
    branches: [ main, actions/add-workflow ]

jobs:
 test-luhn:
    runs-on: ubuntu-latest

    steps:
      - working-directory: wp-content/plugins/wc-invoice-payment-gateway/
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: Luhn Tests
        uses: php-actions/phpunit@v1
        with:
          bootstrap: vendor/autoload.php
          configuration: tests
